# Generated by Django 4.2.3 on 2023-08-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0002_alter_event_category_alter_event_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_logos/"),
        ),
    ]
