# Generated by Django 4.2.3 on 2023-08-10 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventapp", "0005_interested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interested",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested",
                to="eventapp.event",
            ),
        ),
        migrations.AlterField(
            model_name="interested",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
